name: Pull Request Checker

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Validate
        shell: bash
        run: |
          dart pub get
          dart format --set-exit-if-changed lib test
          dart analyze
          dart test
